
base:
  verbose: 1
  save_path: "."
  seed: 42069
  device: "cuda:0"

dataset:
  loc: "todo"

dataloader:
  params:
    batch_size: 128

model:
  config: "./configs/model_config.yaml"
  weights: "./model_weights/diffiqa(r).pth"
