
unet_params:
  dim: 128
  dim_mults: [1, 2, 4, 8]
  channels: 3

diff_params:
  image_size: 112
  timesteps: 1000
  sampling_timesteps: 5
  time_bound: [0, 100]
  loss_type: 'l2'
  objective: 'pred_x0'
  T: 100

trainer_params:
  folder: 'todo'
  train_batch_size: 16
  train_lr: 8.0e-5
  train_num_steps: 100000
  gradient_accumulate_every: 4
  ema_decay: 0.995
  amp: False
  results_folder: "./model_weights/results"
  save_and_sample_every: 500
  use_wandb: 1
  project_name: "diffiqa"
  verbose: 1
